spring:
  application:
    name: Management Service

file:
  upload-dir: ${FILE_UPLOAD_DIR:/data/uploads}
  error-dir: ${FILE_ERROR_DIR:/data/errors}
  retention-days: 30


# Swagger OpenAPI Properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  packages-to-scan: com.tata.cliq.price
  paths-to-match: /api/**

# Server URLs
openapi:
  dev-url: http://localhost:8080
  prod-url: https://api.tatacliq.com
